### PR TITLE
allow embed as content of say()

### PR DESCRIPTION
**Pull request by kowasaur**
this is normally allowed in message.channel.send()

### CODE REVIEW

**Comment by thesilican** [comment]
`MessageEmbed` is part of the `MessageAdditions` type in the second parameter, so you can simply include an embed like this:

```typescript
const embed = new MessageEmbed().setTitle("My message embed"); // etc
msg.say("", embed);
```

**Comment by kowasaur** [comment]
I know but I would prefer if you could just do msg.say(embed) just to make it a bit cleaner.

**Comment by thesilican** [comment]
Version 2.0.0 is published, `msg.say()` call signature matches that of `msg.channel.send()` so you should be able to use `msg.say(embed)`

**Comment by thesilican** [comment]
Also `discord.js` is a peer dependency now which means you may have to manually install it alongside this package

**Comment by kowasaur** [comment]
Thank you

**Pull request closed without merging**
